#! /bin/bash

git clone https://codeberg.org/Limine/Limine.git limine --branch=v10.x-binary --dept=1

make

make -C limine
mkdir -p rootfs

mkdir -p rootfs/boot
cp -v target/bin/aecore rootfs/boot/
mkdir -p rootfs/boot/limine
cp -v limine.conf limine/limine-bios.sys limine/limine-bios-cd.bin limine/limine-uefi-cd.bin rootfs/boot/limine/

mkdir -p rootfs/EFI/BOOT
cp -v limine/BOOTX64.EFI rootfs/EFI/BOOT/
cp -v limine/BOOTIA32.EFI rootfs/EFI/BOOT/

# utility
mkdir -p rootfs/bin
mkdir -p rootfs/lib
mkdir -p rootfs/tmp
mkdir -p rootfs/var
mkdir -p rootfs/home
mkdir -p rootfs/etc

xorriso -as mkisofs -R -r -J -b boot/limine/limine-bios-cd.bin -no-emul-boot -boot-load-size 4 -boot-info-table -hfsplus -apm-block-size 2048 --efi-boot boot/limine/limine-uefi-cd.bin -efi-boot-part --efi-boot-image --protective-msdos-label rootfs -o aeonx.iso

./limine/limine bios-install aeonx.iso

qemu-system-x86_64 -cdrom aeonx.iso -display sdl
